<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Maker_Factory_GeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.maker.factory.generator' shared service.
     *
     * @return \Zenstruck\Foundry\Maker\Factory\FactoryGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Maker/Factory/FactoryGenerator.php';

        return $container->privates['.zenstruck_foundry.maker.factory.generator'] = new \Zenstruck\Foundry\Maker\Factory\FactoryGenerator(($container->privates['.zenstruck_foundry.persistence_manager'] ?? $container->load('get_ZenstruckFoundry_PersistenceManagerService')), ($container->services['kernel'] ?? $container->get('kernel', 1)), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.maker.factory.orm_default_properties_guesser'] ?? $container->load('get_ZenstruckFoundry_Maker_Factory_OrmDefaultPropertiesGuesserService'));
            yield 1 => ($container->privates['.zenstruck_foundry.maker.factory.doctrine_scalar_fields_default_properties_guesser'] ?? $container->load('get_ZenstruckFoundry_Maker_Factory_DoctrineScalarFieldsDefaultPropertiesGuesserService'));
            yield 2 => ($container->privates['.zenstruck_foundry.maker.factory.object_default_properties_guesser'] ?? $container->load('get_ZenstruckFoundry_Maker_Factory_ObjectDefaultPropertiesGuesserService'));
        }, 3), ($container->privates['.zenstruck_foundry.maker.factory.factory_class_map'] ?? $container->load('get_ZenstruckFoundry_Maker_Factory_FactoryClassMapService')), ($container->privates['.zenstruck_foundry.maker.namespace_guesser'] ?? $container->load('get_ZenstruckFoundry_Maker_NamespaceGuesserService')));
    }
}
