<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ECzyG2QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eCzyG2Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eCzyG2Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\CategoryController::getPagination()', 'getCategoryControllergetPaginationService', true],
            'App\\Controller\\CustomerController::getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\CustomerController::getPagination()', 'getCustomerControllergetPaginationService', true],
            'App\\Controller\\EmployeeController::getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\EmployeeController::getPagination()', 'getEmployeeControllergetPaginationService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\ProductController::getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\ProductController::getPagination()', 'getProductControllergetPaginationService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\CategoryController::getPagination()', 'getCategoryControllergetPaginationService', true],
            'App\\Controller\\CustomerController:getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\CustomerController::getPagination()', 'getCustomerControllergetPaginationService', true],
            'App\\Controller\\EmployeeController:getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\EmployeeController::getPagination()', 'getEmployeeControllergetPaginationService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\ProductController:getPagination' => ['privates', '.service_locator.KiIe7k8.App\\Controller\\ProductController::getPagination()', 'getProductControllergetPaginationService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::getPagination' => '?',
            'App\\Controller\\CustomerController::getPagination' => '?',
            'App\\Controller\\EmployeeController::getPagination' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ProductController::getPagination' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:getPagination' => '?',
            'App\\Controller\\CustomerController:getPagination' => '?',
            'App\\Controller\\EmployeeController:getPagination' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ProductController:getPagination' => '?',
        ]);
    }
}
