<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KiIe7k8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KiIe7k8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KiIe7k8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qb' => ['privates', '.errored..service_locator.KiIe7k8.Doctrine\\ORM\\QueryBuilder', NULL, 'Cannot autowire service ".service_locator.KiIe7k8": it references class "Doctrine\\ORM\\QueryBuilder" but no such service exists.'],
        ], [
            'qb' => 'Doctrine\\ORM\\QueryBuilder',
        ]);
    }
}
