<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgoExtensionRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\AgoExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\AgoExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Runtime/AgoExtensionRuntime.php';

        return $container->privates['App\\Twig\\Runtime\\AgoExtensionRuntime'] = new \App\Twig\Runtime\AgoExtensionRuntime();
    }
}
