<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryLogsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CategoryLogsController' shared autowired service.
     *
     * @return \App\Controller\CategoryLogsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AbstractLogsController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CategoryLogsController.php';

        $container->services['App\\Controller\\CategoryLogsController'] = $instance = new \App\Controller\CategoryLogsController(($container->privates['App\\Services\\CategoryService'] ?? $container->load('getCategoryServiceService')), ($container->privates['App\\Services\\DynamoDbService'] ?? $container->load('getDynamoDbServiceService')), ($container->privates['App\\Services\\UserService'] ?? $container->load('getUserServiceService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\CategoryLogsController', $container));

        return $instance;
    }
}
