<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\CategoryService' shared autowired service.
     *
     * @return \App\Services\CategoryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ServicesInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/CategoryService.php';

        return $container->privates['App\\Services\\CategoryService'] = new \App\Services\CategoryService(($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')));
    }
}
