<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllergetPaginationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KiIe7k8.App\Controller\CategoryController::getPagination()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KiIe7k8.App\\Controller\\CategoryController::getPagination()'] = ($container->privates['.service_locator.KiIe7k8'] ?? $container->load('get_ServiceLocator_KiIe7k8Service'))->withContext('App\\Controller\\CategoryController::getPagination()', $container);
    }
}
