<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CartController' shared autowired service.
     *
     * @return \App\Controller\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CartController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/CartService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/CartItemService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/OrderService.php';

        $container->services['App\\Controller\\CartController'] = $instance = new \App\Controller\CartController(new \App\Services\CartService(($container->privates['App\\Repository\\CartRepository'] ?? $container->load('getCartRepositoryService'))), new \App\Services\CartItemService(($container->privates['App\\Repository\\CartItemRepository'] ?? $container->load('getCartItemRepositoryService'))), ($container->privates['App\\Services\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['App\\Services\\ProductService'] ?? $container->load('getProductServiceService')), new \App\Services\OrderService(($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService'))), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\CartController', $container));

        return $instance;
    }
}
