<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamoDbServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\DynamoDbService' shared autowired service.
     *
     * @return \App\Services\DynamoDbService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/DynamoDbService.php';
        include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/DynamoDb/DynamoDbClient.php';

        return $container->privates['App\\Services\\DynamoDbService'] = new \App\Services\DynamoDbService(new \Aws\DynamoDb\DynamoDbClient(['region' => 'us-west-2', 'version' => 'latest', 'endpoint' => 'https://localhost.localstack.cloud:4566', 'credentials' => ['key' => 'test', 'secret' => 'test']]));
    }
}
