<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmployeeController' shared autowired service.
     *
     * @return \App\Controller\EmployeeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FormControllerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AbstractUserController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EmployeeController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ServicesInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/EmployeeService.php';

        $container->services['App\\Controller\\EmployeeController'] = $instance = new \App\Controller\EmployeeController(new \App\Services\EmployeeService(($container->privates['App\\Repository\\EmployeeRepository'] ?? $container->load('getEmployeeRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\EmployeeController', $container));

        return $instance;
    }
}
