<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscribers\OrderEventSubscriber' shared autowired service.
     *
     * @return \App\EventSubscribers\OrderEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscribers/OrderEventSubscriber.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscribers\\OrderEventSubscriber'])) {
            return $container->privates['App\\EventSubscribers\\OrderEventSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscribers\\OrderEventSubscriber'])) {
            return $container->privates['App\\EventSubscribers\\OrderEventSubscriber'];
        }

        return $container->privates['App\\EventSubscribers\\OrderEventSubscriber'] = new \App\EventSubscribers\OrderEventSubscriber(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $a, $b);
    }
}
