<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pagerfanta.view.default' shared service.
     *
     * @return \Pagerfanta\View\DefaultView
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/core/View/ViewInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/core/View/View.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/core/View/TemplateView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/core/View/DefaultView.php';

        return $container->privates['pagerfanta.view.default'] = new \Pagerfanta\View\DefaultView();
    }
}
