<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ProductService' shared autowired service.
     *
     * @return \App\Services\ProductService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ServicesInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ProductService.php';

        return $container->privates['App\\Services\\ProductService'] = new \App\Services\ProductService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
