<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KiIe7k8.Doctrine\ORM\QueryBuilder' shared service.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KiIe7k8": it references class "Doctrine\\ORM\\QueryBuilder" but no such service exists.');
    }
}
