<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRegisteredEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscribers\UserRegisteredEventSubscriber' shared autowired service.
     *
     * @return \App\EventSubscribers\UserRegisteredEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscribers/UserRegisteredEventSubscriber.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscribers\\UserRegisteredEventSubscriber'])) {
            return $container->privates['App\\EventSubscribers\\UserRegisteredEventSubscriber'];
        }

        return $container->privates['App\\EventSubscribers\\UserRegisteredEventSubscriber'] = new \App\EventSubscribers\UserRegisteredEventSubscriber(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $a);
    }
}
