<?php

namespace ContainerR5opYTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscribers\VerificationEventSubscriber' shared autowired service.
     *
     * @return \App\EventSubscribers\VerificationEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscribers/VerificationEventSubscriber.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\EventSubscribers\\VerificationEventSubscriber'])) {
            return $container->privates['App\\EventSubscribers\\VerificationEventSubscriber'];
        }

        return $container->privates['App\\EventSubscribers\\VerificationEventSubscriber'] = new \App\EventSubscribers\VerificationEventSubscriber(($container->services['router'] ?? self::getRouterService($container)), $a);
    }
}
