<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5opYTt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5opYTt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5opYTt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5opYTt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR5opYTt\App_KernelDevDebugContainer([
    'container.build_hash' => 'R5opYTt',
    'container.build_id' => 'f8c28f38',
    'container.build_time' => 1738049507,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5opYTt');
